# Generated by Django 4.1 on 2023-10-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeecrm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
    ]
