# Generated by Django 4.1 on 2023-11-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_employeecrm_employee_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
