# Generated by Django 4.1 on 2023-11-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_employee_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='images',
            new_name='profile_pic',
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
